name: Release CLI package
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: setup pnpm config
      run: pnpm config set store-dir $PNPM_CACHE_FOLDER

    - name: Install dependencies
      run: pnpm install --filter shadcn-fe-cli

    - name: Setup npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc 

    - name: Build and Release CLI
      run: pnpm run build --filter shadcn-fe-cli

    - name: Relaese it CLI 
      run: pnpm  release --ci --filter shadcn-fe-cli

    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
    

